default:
  before_script:
    - echo START_B180910040_START
stages:
  - build
  - deploy
variables:
  GIT_STRATEGY: clone
build:
  stage: build
  tags:
    - deploy-ci
  script:
    - chmod +x ./gradlew
    - ./gradlew build
    - mv build/libs/money_mind.jar /app/money_mind/money_mind.jar
  only:
    - deployment
deploy:
  stage: deploy
  tags:
    - deploy-ci
  script:
    - if [ "$(netstat -tlnp | grep 8080 | wc -l)" -gt 0 ]; then pkill -9 -f money_mind.jar; fi
    - cd /app/money_mind
    - nohup java -jar money_mind.jar --spring.config.name=application --spring.config.location=file:///app/money_mind/ > money_mind.out 2>&1  &
    - echo DONE_B180910040_DONE
    - exit
  only:
    - deployment
